pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "mysql_app"
        TAG = "latest"
        DOCKER_REGISTRY = "tejaswini745"
    }

    stages {
        stage('Docker Build') {
            steps {
                bat """
                    docker build -t %DOCKER_REGISTRY%/%DOCKER_IMAGE%:%TAG% mysql/
                """
            }
        }

        stage('Docker Push') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    bat """
                        echo %DOCKER_PASS% | docker login -u %DOCKER_USER% --password-stdin
                        docker push %DOCKER_REGISTRY%/%DOCKER_IMAGE%:%TAG%
                    """
                }
            }
        }
    }    
}